---
# VIRLR2 Connectivity Variables
ansible_user: "johnny1"
ansible_ssh_pass: "cisco"
ansible_network_os: "ios"
ansible_connection: "network_cli"
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: "cisco"
slainterface: gi0/2